name: Print String Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggers

jobs:
  print_string_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: ab-git-actions/ab-python-action
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          path: ./.github/actions/ab-python-action
        
      - name: Run Custom Action from Private Repo
        uses: ./.github/actions/ab-python-action  # Reference to the private action repo
        with:
          message: 'This is a custom string passed from the workflow!'
        env:
          # To access a private repo, you need a GitHub token
          # Make sure the token has access to the private repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
